---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: cassandra-0
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
